# version: "3.9"

services:
  warehouse:
    image: postgres:15
    env_file:
      - dotenv/postgr.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pipeline

  app:
    image: chik0di/newyorktimes-app
    container_name: extractload-app
    depends_on:
      - warehouse
    env_file:
    - dotenv/.env
    networks:
      - pipeline

  dbt:
    image: chik0di/newyorktimes-dbt
    container_name: dbt-transform
    depends_on:
      - warehouse 
    networks:
      - pipeline
    working_dir: /app
    entrypoint: ["/app/dbt_entrypoint.sh"]

  scheduler:
    image: chik0di/newyorktimes-elt-scheduler
    container_name: nyt-scheduler
    depends_on:
      - app
    env_file:
      - dotenv/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - pipeline
      
networks:
  pipeline:
    driver: bridge

volumes:
  postgres_data: