# version: "3.9"

services:
  warehouse:
    image: postgres:15
    env_file:
      - dotenv/postgr.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pipeline

  app:
    build: ./scripts
    container_name: extractload-app
    depends_on:
      - warehouse
    env_file:
    - dotenv/.env
    networks:
      - pipeline

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: dbt-transform
    depends_on:
      - warehouse 
    volumes:
      - ./dbt/nyt_project:/usr/app
      - $HOME/.dbt:/root/.dbt
    networks:
      - pipeline
    working_dir: /usr/app
    command: run

  scheduler:
    build:
      context: .
      dockerfile: cron/Dockerfile
    image: newyorktimes-elt-scheduler
    container_name: nyt-scheduler
    depends_on:
      - app
    env_file:
      - dotenv/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pipeline
      
networks:
  pipeline:
    driver: bridge

volumes:
  postgres_data: